### ISSUE TITLE
Improve ODE tolerance parameter documentation

### ISSUE THREAD

**Issue by jtimonen** [stan-dev/docs#282] opened 2020-10-31 16:08 UTC
#### Summary:
ODE tolerance parameters and how to set them could be explained more exactly.

#### Description:
Documentation (Section 13.6) says "`relative_tolerance` and `absolute_tolerance` control the stepsize by specifying a target local error that the solver tries to match …"

* It would be good to point out that the methods can only estimate their error (for example the RK45 does it by doing both a 4th and 5th order solve) and the true error is not known. Just to not give users a false sense of security.
* It would be good to show the actual inequality that needs to be satisfied,
as is done [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.RK45.html).
* It would be good to give some reasoning on why the default control parameters are what they are, and in what case they can be OK. Tolerances most likely are not ok, if your solution will be on nanoscale, as was observed [here](https://discourse.mc-stan.org/t/different-ode-solutions-by-integrate-ode-bdf-and-integrate-ode-rk45/15751).

#### Additional Information:
See my Discourse [post](https://discourse.mc-stan.org/t/ode-control-parameter-documentation-questions-and-improvements/18999)  .

#### Current Version:
v2.25

**Comment by yizhang-yiz** [comment] 2020-12-14 20:43
Sorry for leaving this issue hanging for so long. Ping @wds15 who requested issue. Original conversation [here](https://discourse.mc-stan.org/t/ode-control-parameter-documentation-questions-and-improvements/18999).

> It would be good to point out that the methods can only estimate their error (for example the RK45 does it by doing both a 4th and 5th order solve) and the true error is not known. Just to not give users a false sense of security.

+1 to this.

> It would be good to show the actual inequality that needs to be satisfied,

+1 to this too.

> It would be good to give some reasoning on why the default control parameters are what they are, and in what case they can be OK. Tolerances most likely are not ok, if your solution will be on nanoscale, as was observed [here](https://discourse.mc-stan.org/t/different-ode-solutions-by-integrate-ode-bdf-and-integrate-ode-rk45/15751).

Totally agree. This is a disaster(inherited from early implementations no question asked). I want to get rid of default tolerance completely but that requires a greater audience. 

In addition, as you correctly pointed out, the statement
> Relative tolerances are relative to the solution value, whereas absolute tolerances is the maximum absolute error allowed in a solution. Absolute tolerance is more meaningful for ODE solutions that approach zero.

is inaccurate to say at least.

There's an ongoing discussion of adding vector tolerance [here](https://github.com/stan-dev/math/pull/2244). I'd like to avoid making same mistakes in that effort.

**Comment by caesoma** [comment] 2021-01-11 16:36
> * It would be good to point out that the methods can only estimate their error (for example the RK45 does it by doing both a 4th and 5th order solve) and the true error is not known. Just to not give users a false sense of security.

1. For the purpose of Stan documentation I'd think a short explanation of the difference between local and global error should do, with reference to something like [this paper](https://link.springer.com/article/10.1007/s10915-004-4629-3?error=cookies_not_supported&code=da3f493f-da44-4b23-8bbc-e6c7cf359324). So something like this:

` -- this is not the true (global) error, since the analytical solution is not available, but local error obtained by comparing approximations of different order (e.g. fourth and fifth order in RK45) or with smaller time step`

> * It would be good to show the actual inequality that needs to be satisfied,
>   as is done [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.RK45.html).

2. If you mean `atol + rtol * abs(y)` I'm not sure this would be especially useful since it's just saying the local error is smaller than that, but I'd have to know if that is what is actually used [it seems to me that it is often `min( atol, rtol*abs(y)`]

> * It would be good to give some reasoning on why the default control parameters are what they are, and in what case they can be OK. Tolerances most likely are not ok, if your solution will be on nanoscale, as was observed [here](https://discourse.mc-stan.org/t/different-ode-solutions-by-integrate-ode-bdf-and-integrate-ode-rk45/15751).

Is there any objective way of determining the best defaults, or is this a value that works in most cases without compromising efficiency? I'd think it's the latter, so as long as we make a note saying users should be aware of this if their solutions are on the same order of either tolerance, it would be thorough enough.

If this seems reasonable I can draft a proposal and/or create a pull request.

**Comment by jtimonen** [comment] 2021-01-11 19:08
1. Yes, that comment was motivated by the fact that I have seen people thinking that the error is guaranteed to be smaller than some tolerance.

2. I just meant whatever is the rule that is used for accepting the solution.

3. I don't know. It is good to add that note. Another thing is that the BDF solver is probably doing some nonlinear solves when determining what kind of steps to take, and these are also done using some numerical methods which have tolerances. These tolerances are not exposed to users and I don't know how large their effect is on the ODE solution.

**Comment by jtimonen** [comment] 2021-01-11 19:27
Pages 4-5 [here](https://computing.llnl.gov/casc/nsde/pubs/cvs_guide.pdf) seem to describe the math for CVODES. So, the BDF and Adams formulas require solving a nonlinear system. If I understand correctly, the Newton method is used for BDF and some other iterative method with Adams. Anyway, these methods require some rule to determine when they have converged and I don't know how the error in solving *G(y_n) = 0* propagates to the ODE solution.

**Comment by caesoma** [comment] 2021-01-14 15:32
For the purpose of a user guide I think the higher level explanation should suffice; at some point you must defer to the technical papers, and the documentation cites some references (more could be added if needed).

**Comment by yizhang-yiz** [comment] 2021-01-14 22:59
It's always a struggle how much algorithm details should be exposed in the doc, and I agree at some point it's eventually user's responsibility. That being said, moving the presentation a bit deeper sometimes can help a lot, especially for args like tolerance that could potentially ruin the fitting. I believe this would be consistent with current doc style: perhaps all users are familiar with "linear regression" and yet we still [present the equation](https://mc-stan.org/docs/2_25/stan-users-guide/linear-regression.html) to facilitate discussion. 

So for items listed above, IMO it helps to
- "point out that the methods can only estimate their error". 
- " to show the actual inequality that needs to be satisfied" .

With the above information, sentence like
> whereas absolute tolerances is the maximum absolute error allowed in a solution. Absolute tolerance is more meaningful for ODE solutions that approach zero.

in current doc becomes much easier to digest.

On the other hand, the default tolerance is by no means objective. I'd rather like to see it a legacy rather than recommendation.

**Comment by yizhang-yiz** [comment] 2021-01-15 17:35
I'm closing this for the moment per approval of PR #311 but I'd like to keep discussion going, so please post on the original discouse thread if more doc tuning/clarification is needed.

**Closed by yizhang-yiz** 2021-01-15 17:35 UTC
